version: "3.8"

services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
      POSTGRES_DB: taskmanager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U taskuser" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
